# Generated by Django 3.2.6 on 2021-08-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.PositiveBigIntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('pincode', models.PositiveIntegerField(blank=True)),
                ('type_of_customer', models.CharField(choices=[('individual', 'individual'), ('professional', 'professional')], default='individual', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='DistributionRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_milk', models.CharField(choices=[('cow', 'cow'), ('buffalo', 'buffalo')], default='cow', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('litre', 'litre'), ('kilogram', 'kilogram')], default='litre', max_length=100)),
                ('time_of_delivery', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], default='morning', max_length=100)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.customers')),
            ],
            options={
                'verbose_name_plural': 'Distribution_Required',
            },
        ),
        migrations.CreateModel(
            name='DailyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], default='morning', max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('delivered_at', models.DateField(default=0)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.customers')),
            ],
            options={
                'verbose_name_plural': 'Daily_Distribution',
            },
        ),
    ]
