# Generated by Django 3.2.6 on 2021-08-03 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydistribution',
            name='delivered_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
