# Generated by Django 3.2.6 on 2021-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_dailydistribution_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionrequired',
            name='time_of_delivery',
            field=models.CharField(choices=[('morning', 'morning'), ('evening', 'evening'), ('both', 'both')], default='morning', max_length=100),
        ),
    ]
