# Generated by Django 3.2.6 on 2021-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_distributionrequired_time_of_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydistribution',
            name='time_period',
        ),
        migrations.AddField(
            model_name='dailydistribution',
            name='type_of_milk',
            field=models.CharField(choices=[('cow', 'buffalo'), ('cow', 'buffalo')], default='cow', max_length=100),
        ),
    ]
