# Generated by Django 3.2.6 on 2021-08-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210803_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydistribution',
            name='type_of_milk',
            field=models.CharField(choices=[('cow', 'cow'), ('buffalo', 'buffalo')], default='cow', max_length=100),
        ),
    ]
